[tool.ruff]
ignore = [
    "E501",
    "E741",
	"RET501",
    ]
extend-select = [
    "ARG",
    "C4", 
    "ERA",
    "RET",
    "SIM",
    "TCH",
    ]

target-version = "py310"


[tool.ruff.mccabe]
max-complexity = 10
